# Generated by Django 3.2 on 2021-05-06 22:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
