# Generated by Django 3.2 on 2021-05-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_images_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='description',
            new_name='detail',
        ),
    ]
