# Generated by Django 3.2 on 2021-05-07 22:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_description_images_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
